title: Just the Docs sobota 24.02
description: Zajęcia z Just the Docs sobota 24.02
theme: just-the-docs
color_scheme: dark

url: https://baraszot.github.io/jtd_sobota

aux_links:
  Template Repository: https://github.com/baraszot/jtd_sobota
